version: '3.7'


services:

  kubectl:
    environment:
      KUBECONFIG: /code/kubeconfig_awesome
  helm:
    environment:
      KUBECONFIG: /code/kubeconfig_awesome
  helmfile:
    environment:
      KUBECONFIG: /code/kubeconfig_awesome

volumes:
  aws-creds:
    name: aws-creds
  helm-config:
  helm-cache: